# Generated by Django 2.2.10 on 2020-04-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdek', '0002_auto_20200416_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AddField(
            model_name='deliverypoint',
            name='work_time',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Режим работы'),
        ),
    ]
