# Generated by Django 2.2.10 on 2020-04-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdek', '0003_auto_20200416_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverypoint',
            old_name='owner_сode',
            new_name='owner_code',
        ),
    ]
