# Generated by Django 2.2.10 on 2020-04-26 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdek', '0004_auto_20200416_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypoint',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverypoints', to='cdek.City', verbose_name='Населенный пункт'),
        ),
    ]
